<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="26" started-at="2012-03-13T09:04:16Z" finished-at="2012-03-13T09:04:16Z">
    <groups>
      <group name="BVT">
        <method signature="Module1Test.testMethod2()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod2" class="Module1Test"/>
      </group> <!-- BVT -->
      <group name="P1">
        <method signature="Module1Test.testMethod1()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod1" class="Module1Test"/>
        <method signature="Module1Test.testMethod3()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod3" class="Module1Test"/>
      </group> <!-- P1 -->
      <group name="P2">
        <method signature="Module1Test.testMethod2()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod2" class="Module1Test"/>
      </group> <!-- P2 -->
      <group name="FVT">
        <method signature="Module1Test.testMethod1()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod1" class="Module1Test"/>
        <method signature="Module1Test.testMethod3()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod3" class="Module1Test"/>
      </group> <!-- FVT -->
    </groups>
    <test name="Command line test" duration-ms="26" started-at="2012-03-13T09:04:16Z" finished-at="2012-03-13T09:04:16Z">
      <class name="Module1Test">
        <test-method status="PASS" signature="testMethod1()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod1" duration-ms="8" started-at="2012-03-13T09:04:16Z" finished-at="2012-03-13T09:04:16Z">
        </test-method> <!-- testMethod1 -->
        <test-method status="FAIL" signature="testMethod2()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod2" duration-ms="1" started-at="2012-03-13T09:04:16Z" finished-at="2012-03-13T09:04:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<1> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<1> but was:<2>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at Module1Test.testMethod2(Module1Test.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1170)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1095)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:60)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:106)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at $Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- testMethod2 -->
        <test-method status="PASS" signature="testMethod3()[pri:0, instance:Module1Test@7a5e1077]" name="testMethod3" duration-ms="0" started-at="2012-03-13T09:04:16Z" finished-at="2012-03-13T09:04:16Z">
        </test-method> <!-- testMethod3 -->
      </class> <!-- Module1Test -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
